const LOGIN = "LOGIN";
const LOGIN_SUCCESS = "LOGIN_SUCCESS";
const LOGIN_FAIL = "LOGIN_FAIL";

const SIGNUP = "SIGNUP";
const SIGNUP_SUCCESS = "SIGNUP_SUCCESS";
const SIGNUP_FAIL = "SIGNUP_FAIL";

const LOGOUT = "LOGOUT";
const LOGOUT_SUCCESS = "LOGOUT_SUCCESS";
const LOGOUT_FAIL = "LOGOUT_FAIL";
const GET_COLORS = "GET_COLORS";

const OPENMODAL = "OPENMODAL";

const SET_USER_DATA = "SET_USER_DATA";
const GET_COUNTRIES = "GET_COUNTRIES";
const GET_CITIES = "GET_CITIES";

const SHOWLOADER = "SHOWLOADER";
const HIDELOADER = "HIDELOADER";

const GETCATEGORIES = "GETCATEGORIES";
const GETSUBCATEGORIES = "GETSUBCATEGORIES";
const GETWISHLIST = "GETWISHLIST";

const ADDTOCART = "ADDTOCART";
const CLEARCART = "CLEARCART";

const REMOVEFROMCART = "REMOVEFROMCART";
const UPDATETOCART = "UPDATETOCART";
const VERIFYCART = "VERIFYCART";
const ADDPLACEMENT = "ADDPLACEMENT";
const ADD_GIFTSET_PLACEMENT = "ADD_GIFTSET_PLACEMENT";
const UPDATE_GIFTSET_PLACEMENT = "UPDATE_GIFTSET_PLACEMENT";

const SAVESHIPPING = "SAVESHIPPING";
const SAVESHIPPINGADRESSS = "SAVESHIPPINGADRESSS";

const SETPROFILE = "SETPROFILE";
const REMOVEPLACEMENT = "REMOVEPLACEMENT";
const REMOVE_GIFTSET_PLACEMENT = "REMOVE_GIFTSET_PLACEMENT";
const UPDATEPLACEMENT = "UPDATEPLACEMENT";

const SET_CURRENCY = "SET_CURRENCY";

export {
  LOGIN,
  LOGIN_SUCCESS,
  LOGIN_FAIL,
  SIGNUP,
  SIGNUP_SUCCESS,
  SIGNUP_FAIL,
  LOGOUT,
  LOGOUT_SUCCESS,
  LOGOUT_FAIL,
  OPENMODAL,
  CLEARCART,
  SET_USER_DATA,
  SHOWLOADER,
  HIDELOADER,
  GETCATEGORIES,
  GETSUBCATEGORIES,
  GET_COLORS,
  SAVESHIPPINGADRESSS,
  ADDTOCART,
  REMOVEFROMCART,
  GETWISHLIST,
  UPDATETOCART,
  GET_COUNTRIES,
  GET_CITIES,
  VERIFYCART,
  ADDPLACEMENT,
  ADD_GIFTSET_PLACEMENT,
  SAVESHIPPING,
  SETPROFILE,
  REMOVEPLACEMENT,
  UPDATEPLACEMENT,
  REMOVE_GIFTSET_PLACEMENT,
  UPDATE_GIFTSET_PLACEMENT,
  SET_CURRENCY,
};
